config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'books/new'
  post 'books' => 'books#create'
  get 'books/index' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id/update' => 'books#update', as: 'update_book'
  get 'books/book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
  validates :body, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @books = Book.all
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    
    if @book.save
      redirect_to book_path(@book.id), notice: 'successfully'
    else
      @books = Book.all
      render :index
    end
  end  

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
     @book = Book.find(params[:id])
     @book.update(book_params)
     if @book.save
      redirect_to book_path(@book.id), notice: 'successfully'
     else
       render :edit
     end 
  end


  def book
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to'/books'
  end  
  
  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/flash_controller.rb
class FlashController < ApplicationController
  def flash1
    flash[:success] = "successfully"
  end

  def flash2
  end

  def flash3
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @lists = Book.all
    @list = Book.new
  end
  
  def create
    @list = Book.new(list_params)
    
    if @list.save
      redirect_to list_path(@list.id), notice: 'successfully'
    else
      @lists = Book.all
      render :books_path
    end
  end  

  def index
  end

  def show
    @list = Book.find(params[:id])
  end

  def edit
    @list = Book.find(params[:id])
  end
  
  def update
     list = Book.find(params[:id])
     list.update(list_params)
     redirect_to list_path(list.id), notice: 'successfully'
  end


  def book
  end
  
 
  private
  
  def list_params
    params.require(:book).permit(:title, :body)
  end
  
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/flash_helper.rb
module FlashHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/book.html.erb
<h1>Lists#book</h1>
<p>Find me in app/views/lists/book.html.erb</p>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
 <h4>Title</h4>
  <%= f.text_field :title %>
  
  <h4>Body</h4>
  <%= f.text_area :body %>
  
  <%= f.submit 'Update Book' %>
<% end %>

<span><%= link_to "show", book_path(@book.id) %></span>
|
<span><%= link_to "Back", "/books" %></span>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
<theat>
 <tr>
  <th>Title</th>
  <th>Body</th>
  <th colspan="3"></th>
 </tr>
</theat>

<tbody>
  <% @books.each do |book| %>
   <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "Show", book_path(book.id) %></td>
    <td><%= link_to "Edit", edit_book_path(book.id) %></td>
    <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>>

   </tr> 
  <% end %>
 </tbody>
</table>
<h2>New book<h2>
 
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book,url: books_path, method: :post, local: true do |f| %>
 <div>
  <%= f.label :title %>
  <%= f.text_field :title %>
	</div>
	<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
	<div>
  <%= f.submit 'Create Book' %>
<% end %>
  

app/views/books/new.html.erb
<h1>Books</h1>
<table>
<theat>
 <tr>
  <th>Title</th>
  <th>Body</th>
  <th colspan="3"></th>
 </tr>
</theat>

<tbody>
  <% @lists.each do |list| %>
   <tr>
    <td><%= list.title %></td>
    <td><%= list.body %></td>
    <td><%= link_to "Show", book_path(list.id) %></td>
    <td><%= link_to "Edit", edit_book_path(list.id) %></td>
    <td><%= link_to "Destroy", book_path(list.id), method: :delete, "data-confirm" => "Are you sure?" %></td>>

   </tr>
  <% end %>
 </tbody>
</table>
<h2>New book<h2>

 <% if @list.errors.any? %>
  <%= @list.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @list,url: books_path, method: :post, local: true do |f| %>
 <div>
  <%= f.label :title %>
  <%= f.text_field :title %>
	</div>
	<div>
  <%= f.label :body %>
  <%= f.text_area :body %>
	<div>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<%= notice %>
<body>
<div>
<strong>Title:</strong> 
<%= @book.title %>
</div>

<div>
<strong>Body:</strong> 
<%= @book.body %>
</div>
</body>
<span><%= link_to "Edit", edit_book_path(@book.id) %></span>
|
<span><%= link_to "Back", "/books" %></span>

app/views/flash/flash1.html.erb
<h1>Flash#flash1</h1>
<p>Find me in app/views/flash/flash1.html.erb</p>

app/views/flash/flash2.html.erb
<h1>Flash#flash2</h1>
<p>Find me in app/views/flash/flash2.html.erb</p>

app/views/flash/flash3.html.erb
<h1>Flash#flash3</h1>
<p>Find me in app/views/flash/flash3.html.erb</p>

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>
<p>bookersでは、さまざまな書籍に関するあなたの意見や印象を共有し<br>交換することができます</p>

<span>
 <%= link_to "start","/books" %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>